services:
  playstats-bot:
    container_name: playstats-bot
    image: playstats-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
    restart: always
    networks:
      - playstats-network
    volumes:
      - .env:/app/.env

networks:
  playstats-network:
    external: true 